In [4]:
import gym
import numpy as np

In [2]:
env = gym.make('MountainCar-v0')

In [3]:
env.reset()

array([-0.59607387,  0.        ])

In [9]:


def create_tiling(feat_range, bins, offset):
    """
    Create 1 tiling spec of 1 dimension(feature)
    feat_range: feature range; example: [-1, 1]
    bins: number of bins for that feature; example: 10
    offset: offset for that feature; example: 0.2
    """
    
    return np.linspace(feat_range[0], feat_range[1], bins+1)[1:-1] + offset
  
feat_range = [0, 1.0]
bins = 10
offset = 0.2

tiling_spec = create_tiling(feat_range, bins, offset)

# array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1])

np.linspace(feat_range[0], feat_range[1], bins+1)[1:-1]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [10]:
def create_tilings(feature_ranges, number_tilings, bins, offsets):
        """
        feature_ranges: range of each feature; example: x: [-1, 1], y: [2, 5] -> [[-1, 1], [2, 5]]
        number_tilings: number of tilings; example: 3 tilings
        bins: bin size for each tiling and dimension; example: [[10, 10], [10, 10], [10, 10]]: 3 tilings * [x_bin, y_bin]
        offsets: offset for each tiling and dimension; example: [[0, 0], [0.2, 1], [0.4, 1.5]]: 3 tilings * [x_offset, y_offset]
        """
        tilings = []
        # for each tiling
        for tile_i in range(number_tilings):
            tiling_bin = bins[tile_i]
            tiling_offset = offsets[tile_i]

            tiling = []
            # for each feature dimension
            for feat_i in range(len(feature_ranges)):
                feat_range = feature_ranges[feat_i]
                # tiling for 1 feature
                feat_tiling = create_tiling(feat_range, tiling_bin[feat_i], tiling_offset[feat_i])
                tiling.append(feat_tiling)
            tilings.append(tiling)
        return np.array(tilings)
 
feature_ranges = [[-1, 1], [2, 5]]  # 2 features
number_tilings = 3
bins = [[10, 10], [10, 10], [10, 10]]  # each tiling has a 10*10 grid
offsets = [[0, 0], [0.2, 1], [0.4, 1.5]]

tilings = create_tilings(feature_ranges, number_tilings, bins, offsets)

print(tilings.shape)  # # of tilings X features X bins

# (3, 2, 9)

(3, 2, 9)


In [11]:
tilings

array([[[-8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
         -2.00000000e-01,  0.00000000e+00,  2.00000000e-01,
          4.00000000e-01,  6.00000000e-01,  8.00000000e-01],
        [ 2.30000000e+00,  2.60000000e+00,  2.90000000e+00,
          3.20000000e+00,  3.50000000e+00,  3.80000000e+00,
          4.10000000e+00,  4.40000000e+00,  4.70000000e+00]],

       [[-6.00000000e-01, -4.00000000e-01, -2.00000000e-01,
          5.55111512e-17,  2.00000000e-01,  4.00000000e-01,
          6.00000000e-01,  8.00000000e-01,  1.00000000e+00],
        [ 3.30000000e+00,  3.60000000e+00,  3.90000000e+00,
          4.20000000e+00,  4.50000000e+00,  4.80000000e+00,
          5.10000000e+00,  5.40000000e+00,  5.70000000e+00]],

       [[-4.00000000e-01, -2.00000000e-01,  1.11022302e-16,
          2.00000000e-01,  4.00000000e-01,  6.00000000e-01,
          8.00000000e-01,  1.00000000e+00,  1.20000000e+00],
        [ 3.80000000e+00,  4.10000000e+00,  4.40000000e+00,
          4.70000000e+00,  5.00

In [48]:
low = env.observation_space.low[0]; high = env.observation_space.high[0] 

In [57]:
def create_tiling(low, high, no_tiles, offset):
    return np.linspace(low, high, no_tiles) + offset

In [55]:
offset = (high - low) / no_tiles
offset

0.45000001788139343

In [67]:
no_tiles = 4
low = env.observation_space.low[0]; high = env.observation_space.high[0]


def create_tilings(low, high, no_tiles):
    
    offset = (high - low) / no_tiles / no_tiles
    tilings = []
    for t in range(no_tiles):
        tiling = np.linspace(low, high, no_tiles) + offset * t
        tilings.append(tiling)
    return tilings


tiling_pos = create_tilings(low, high, no_tiles)
tiling_pos

[array([-1.20000005, -0.60000002,  0.        ,  0.60000002]),
 array([-1.08750004, -0.48750002,  0.1125    ,  0.71250003]),
 array([-0.97500004, -0.37500001,  0.22500001,  0.82500003]),
 array([-0.86250003, -0.26250001,  0.33750001,  0.93750004])]

In [110]:
pos = -1.19
vector = np.empty(0, dtype=np.int16)
for tile in tiling_pos:
    idx = np.where(tile > pos)[0][0]
    vector = np.append(vector, np.eye(no_tiles, dtype=np.int16)[idx])

print(vector)

[0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0]


In [108]:
np.empty(0, dtype=np.int16)

array([], dtype=int16)

In [86]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.where(3 >= arr)[0][0]

0